version: '3.8'
services:
  algothon-quant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js frontend
      - "5000:5000"  # MLflow UI
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - NODE_ENV=production 